### ISSUE TITLE
Image upload from localhost failes

### ISSUE THREAD

**Issue by mgoldboi** [oVirt/ovirt-ansible-image-template#17]
Release 1.1.7

TASK [oVirt.image-template : Deploy the qcow image to oVirt engine] ***********************************************************************************************************************************************
task path: /home/mgoldboi/git/oVirt.image-template/tasks/qcow2_image.yml:82
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/_ovirt_disks.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mgoldboi
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894 `" && echo ansible-tmp-1530130980.63-39375260084894="` echo /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894 `" ) && sleep 0'
<127.0.0.1> PUT /home/mgoldboi/.ansible/tmp/ansible-local-677p_OE1G/tmpLIVUTT TO /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894/_ovirt_disks.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894/ /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894/_ovirt_disks.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894/_ovirt_disks.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/mgoldboi/.ansible/tmp/ansible-tmp-1530130980.63-39375260084894/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_U1Kvsm/ansible_module_ovirt_disks.py", line 629, in main
    uploaded = upload_disk_image(connection, module)
  File "/tmp/ansible_U1Kvsm/ansible_module_ovirt_disks.py", line 431, in upload_disk_image
    transfer_func=_transfer,
  File "/tmp/ansible_U1Kvsm/ansible_module_ovirt_disks.py", line 316, in transfer
    proxy_url = urlparse(transfer.proxy_url)
  File "/usr/lib64/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.7/urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'

[DEPRECATION WARNING]: The 'ovirt_disks' module is being renamed 'ovirt_disk'. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth": {
                "ca_file": null, 
                "compress": true, 
                "headers": null, 
                "insecure": true, 
                "kerberos": false, 
                "timeout": 0, 
                "token": "tipwXuZbWLzrG3u1jywnLmd3ILQrCr3adj0kqTuQMiH0bVxtHFd2t42MPglQrY9M79vo4ZTKgP714h3ceIIoBA", 
                "url": "https://rhevm.eng.lab.tlv.redhat.com/ovirt-engine/api"
            }, 
            "bootable": null, 
            "description": null, 
            "download_image_path": null, 
            "fetch_nested": false, 
            "force": true, 
            "format": "cow", 
            "id": "223aced0-63a5-43e2-aac2-406417676a74", 
            "image_path": "/tmp/rhel-server-7.5-x86_64-kvm.qcow2?_auth_=***", 
            "image_provider": null, 
            "interface": null, 
            "logical_unit": null, 
            "name": "mgoldboi-rhel75", 
            "nested_attributes": [], 
            "openstack_volume_type": null, 
            "poll_interval": 3, 
            "profile": null, 
            "quota_id": null, 
            "shareable": null, 
            "size": "10GiB", 
            "sparse": null, 
            "sparsify": null, 
            "state": "present", 
            "storage_domain": "RHEV-TLV-STORAGE-ISCSI", 
            "storage_domains": null, 
            "timeout": 180, 
            "upload_image_path": "/tmp/rhel-server-7.5-x86_64-kvm.qcow2?_auth_=***", 
            "vm_id": null, 
            "vm_name": null, 
            "wait": true
        }
    }, 
    "msg": "'NoneType' object has no attribute 'find'"
}
Read vars_file 'passwords.yml'

**Comment by machacekondra** [comment]
Can you check `/var/log/ovirt-imageio-proxy/image-proxy.log`. And also check if service `ovirt-imageio-proxy` is up and running.

**Comment by mykaul** [comment]
This is strange:
```
"image_path": "/tmp/rhel-server-7.5-x86_64-kvm.qcow2?auth=***
```

Can you share the role?

**Comment by mgoldboi** [comment]
@machacekondra no access to this system logs, test connection on the UI worked fine.

**Comment by machacekondra** [comment]
@mgoldboi I just noticed , you are not sending `ca_file` it's must for imageio.

**Comment by mgoldboi** [comment]
@machacekondra tried with a CA file as well, same error, relevant to first try (new image name)
operation is stuck on engine side on finalizing state. when try to rerun, execution fails on timeout.

aside from this issue, If CA is required for this role, shouldn't we fail if it's not provided? just to avoid those scenarios.

TASK [oVirt.image-template : Login to oVirt] **********************************************************************************************************************************************************************
task path: /home/mgoldboi/git/oVirt.image-template/tasks/qcow2_image.yml:41
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_auth.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mgoldboi
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594 `" && echo ansible-tmp-1530173958.12-190504412361594="` echo /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594 `" ) && sleep 0'
<127.0.0.1> PUT /home/mgoldboi/.ansible/tmp/ansible-local-8379WXUpdc/tmpWM3IJ5 TO /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594/ovirt_auth.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594/ /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594/ovirt_auth.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594/ovirt_auth.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/mgoldboi/.ansible/tmp/ansible-tmp-1530173958.12-190504412361594/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "ansible_facts": {
        "ovirt_auth": {
            "ca_file": "/home/mgoldboi/Downloads/pki-resource", 
            "compress": true, 
            "headers": null, 
            "insecure": true, 
            "kerberos": false, 
            "timeout": 0, 
            "token": "qovs1TJkndtApMXDbLmVJwPdYmKZhClM4jjeua8UgRPQ9t3VzKQBFCet0VnBz-VQVqXhztC8jzzafRD8AzKTzg", 
            "url": "https://rhevm.***.com/ovirt-engine/api"
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "ca_file": "/home/mgoldboi/Downloads/pki-resource", 
            "compress": true, 
            "headers": null, 
            "insecure": true, 
            "kerberos": false, 
            "ovirt_auth": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "timeout": 0, 
            "token": null, 
            "url": "https://rhevm.***.com/ovirt-engine/api", 
            "username": "mgoldboi@redhat.com"
        }
    }
}
Read vars_file 'passwords.yml'

**Comment by arendej** [comment]
The cert for auth is not required as long as your manager doesn't force https. I have that commented out and the auth works.

**Comment by ironreality** [comment]
Have the same issue too. Release 1.1.8, engine_cafile is set.
As I see it's not a role's bug, it reproduces too when use ovirt_disk Ansible's module directly.

**Comment by ironreality** [comment]
The cause of the issue laid in ovirt-imageio-proxy misconfiguration, namely ImageProxyAddress parameter. Fixed it with the next commands:

`engine-config -s ImageProxyAddress=your.ovirtengine.hostname:54323`
`systemctl restart ovirt-engine.service`
`systemctl restart ovirt-imageio-proxy.service`

**Comment by mnecas** [comment]
Looks like everything was resolved. If necessary reopen the issue.
