### ISSUE TITLE
loading in rhel images

### ISSUE THREAD

**Issue by arendej** [oVirt/ovirt-ansible-image-template#30]
Seeing as how RHEL images are behind the Red Hat login wall, I solved for this by

1. download rhel7 qcow2 image to local laptop
2. expose that file via local apache
3. use local apache qcow2 image address as the 'URL' of the qcow2 image in the role playbook
4. profit

Are there plans of making that less 'hacky' in any way?.. maybe some kid of localhost image pull?

**Comment by johnsimcall** [comment]
If I recall correctly, you can simply download the file and reference it via local uri.  For example, qcow_url: file:///nfs-mount/vm-images/rhel-server-7.5-x86_64-kvm.qcow2

N.B. There are three slashes after "file:"

**Comment by machacekondra** [comment]
As per comment above using a `file:///` is a solution, closing.
