### ISSUE TITLE
Feature Request: Multiple Disk Support

### ISSUE THREAD

**Issue by mordechai** [oVirt/ovirt-ansible-image-template#32]
Would be useful to be able to supply a variable containing a lists of [disks](https://github.com/oVirt/ovirt-ansible-image-template/blob/master/tasks/qcow2_image.yml#L118) which should be attached to vm before template is made so that multiple disks could be part of the template instead of a single disk.

The presence of the disks would be the user's responsibility, but attaching disks from within this role via role level variable might be useful for those making templates which references many disks.

**Comment by machacekondra** [comment]
@mnecas

**Comment by mnecas** [comment]
Released in 1.2.2
