### ISSUE TITLE
There is no error handler for checking template creation

### ISSUE THREAD

**Issue by acidorius** [oVirt/ovirt-ansible-image-template#37]
While creating the template the error can appear like this:

> [320b0bfb-7a80-405d-9cd7-8966a34be036]  Command 'AddVmTemplate' 
> id: 'cf34b7a3-1b56-466e-a6fd-99c81af08b46' child commands '[8ddfa952-c73a-4e8d-ad63-8c44d24029f3]' executions were completed, status 'FAILED'
> [320b0bfb-7a80-405d-9cd7-8966a34be036]  EVENT_ID: USER_ADD_
> VM_TEMPLATE_CREATE_TEMPLATE_FAILURE(1,322), Failed to create Template template or its disks from VM temporary_vm_name_12367123.

But the role doesn't react on that, only giving the timeout error:

> TASK [ovirt.image-template : Create template] *********************************************************************************************************************************************************************
> task path: /home/user/iac-basevm-template/deploy/roles/ovirt.image-template/tasks/qcow2_image.yml:186
> Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/ovirt/ovirt_template.py
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
> <localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
> The full traceback is:
> Traceback (most recent call last):
>   File "/tmp/ansible_ovirt_template_payload_adie1lk_/__main__.py", line 491, in main
>     seal=module.params['seal'],
>   File "/tmp/ansible_ovirt_template_payload_adie1lk_/ansible_ovirt_template_payload.zip/ansible/module_utils/ovirt.py", line 610, in create
>     poll_interval=self._module.params['poll_interval'],
>   File "/tmp/ansible_ovirt_template_payload_adie1lk_/ansible_ovirt_template_payload.zip/ansible/module_utils/ovirt.py", line 341, in wait
>     raise Exception("Timeout exceed while waiting on result state of the entity.")
> Exception: Timeout exceed while waiting on result state of the entity.
> 
> fatal: [localhost]: FAILED! => {
>     "changed": false, 
>     "invocation": {
>         "module_args": {
>             "allow_partial_import": null, 
>             "clone_permissions": null, 
>             "cluster": "Development", 
>             "cluster_mappings": [], 
>             "cpu_profile": null, 
>             "description": null, 
>             "domain_mappings": [], 
>             "exclusive": null, 
>             "export_domain": null, 
>             "fetch_nested": false, 
>             "id": null, 
>             "image_disk": null, 
>             "image_provider": null, 
>             "io_threads": null, 
>             "memory": null, 
>             "memory_guaranteed": null, 
>             "memory_max": null, 
>             "name": "template", 
>             "nested_attributes": [], 
>             "operating_system": null, 
>             "poll_interval": 3, 
>             "role_mappings": [], 
>             "seal": true, 
>             "state": "present", 
>             "storage_domain": null, 
>             "template_image_disk_name": null, 
>             "timeout": 1200, 
>             "vm": "temporary_vm_name_12367123", 
>             "vnic_profile_mappings": [], 
>             "wait": true
>         }
>     }, 
>     "msg": "Timeout exceed while waiting on result state of the entity."
> }
> Read vars_file '../ovirt_engine_vars.yml'

There should be some error handler, so we know whether template created or not and don't need to wait until timeout reached (also timeout give us no direct information about status of the event).

**Comment by machacekondra** [comment]
Fixed by: https://github.com/oVirt/ovirt-ansible-image-template/pull/34
