### ISSUE TITLE
Wait for resize failed

### ISSUE THREAD

**Issue by sradco** [oVirt/ovirt-ansible-image-template#46]
Parameterise "retries" and "delay" in the  "Wait for resize" task.
https://github.com/oVirt/ovirt-ansible-image-template/blob/f423c3a0aa279cdf43b75946b562b1ba7618193d/tasks/qcow2_image.yml#L191
https://github.com/oVirt/ovirt-ansible-image-template/blob/f423c3a0aa279cdf43b75946b562b1ba7618193d/tasks/qcow2_image.yml#L192

**Comment by machacekondra** [comment]
@mnecas Can you please add new variable called `disk_resize_timeout`? Which will be by default 1min. Change dealy to 3sec and retries count as `disk_resize_timeout / 3`

**Comment by mnecas** [comment]
@machacekondra What if i would use `timeout: retries_var * delay_var`? 
And default value of `timeout` is 300s so it is bit strange that it fails.
https://docs.ansible.com/ansible/latest/modules/wait_for_module.html

**Comment by machacekondra** [comment]
Wait doesn't work for 'update' (PUT) operation. So `timeout` parameter doesn't work in this case.
