### ISSUE TITLE
Don't download the image if the template already exists

### ISSUE THREAD

**Issue by timbrd** [oVirt/ovirt-ansible-image-template#69]
I use the ansible role inside a container which is being orchestrated by gitlab ci to manage my virtual machines.
Since the container is created each time the ci task runs and the container does not contain the template image, the image is being downloaded.

How about checking if the template already exists on the ovirt cluster and then decide if it is neccessary to download the image?

**Comment by mnecas** [comment]
You can define `image_checksum` to check if the image was properly downloaded, if so the download will be skipped.
Or you can use `pre_tasks` as in README where you can use your logic to skip the download when file is existing.
I'll probably update the README to include this example.

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
