### ISSUE TITLE
Please provide an example of a playbook to use with template_prerequisites_tasks

### ISSUE THREAD

**Issue by flyemsafe** [oVirt/ovirt-ansible-image-template#73]
Hello,

This setting seems like I can use it to set the root password and ssh keys on the template. Is it just any functioning playbook that would normally work on a running system?

Thanks

**Comment by flyemsafe** [comment]
Ok, it does appear I can just include a task file. However, it seems as though access to the VM to run the tasks is being denied.

```
TASK [ovirt.image-template : Add test user] ************************************************
Monday 24 August 2020  22:07:08 -0400 (0:00:00.049)       0:02:39.933 ********* 
fatal: [localhost]: UNREACHABLE! => changed=false 
  msg: |-
    Invalid/incorrect password: Warning: Permanently added '172.23.60.101' (ECDSA) to the list of known hosts.
    Load key "/tmp/.image_template.key": Permission denied
    Permission denied, please try again.
  unreachable: true
```

**Comment by mnecas** [comment]
Hi @flyemsafe, 
could you please try my patch if it fixes your issue?

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
